### PR TITLE
Update Storage portion in DG

### PR DESCRIPTION
**Pull request by notle1706**

### CODE REVIEW

**Review by ElginL — COMMENTED** [review]
Diagrams looks correct, but I'm interested to know why you decided to split the Storage into 2 different diagrams?

**Review by jicsontoh — APPROVED** [review]
LGTM!

**Comment by notle1706** [comment]
> Diagrams looks correct, but I'm interested to know why you decided to split the Storage into 2 different diagrams?

I feel that the diagram would be too big and complicated if it were not split into 2 different diagrams.

**Review by ElginL — APPROVED** [review]
LGTM

**Pull request merged**
